definitions:
  commonModels.ResponseData:
    properties:
      code:
        description: 相应状态码
        type: integer
      data:
        description: 数据
      msg:
        description: 提示信息
        type: string
    type: object
  systemModels.LoginBody:
    properties:
      code:
        description: 验证码
        type: string
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
      uuid:
        description: uuid
        type: string
    required:
    - code
    - password
    - username
    - uuid
    type: object
info:
  contact:
    email: zhao_402295440@126.com
    name: danny
  description: baize接口文档
  title: baize
  version: 2.0.x
paths:
  /login:
    post:
      description: 用户登录
      parameters:
      - description: 登录信息
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/systemModels.LoginBody'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            $ref: '#/definitions/commonModels.ResponseData'
        "412":
          description: 参数错误
          schema:
            $ref: '#/definitions/commonModels.ResponseData'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/commonModels.ResponseData'
        "601":
          description: 用户名密码错误
          schema:
            $ref: '#/definitions/commonModels.ResponseData'
      summary: 用户登录
      tags:
      - 管理端登录
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
