// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func wireApp() (*gin.Engine, func(), error) {

	engine := newApp()
	return engine, func() {
		cleanup()
	}, nil
}
