// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/bzdanny/BaiZe/app/monitor/monitorController"
	"github.com/bzdanny/BaiZe/app/monitor/monitorDao/monitorDaoImpl"
	"github.com/bzdanny/BaiZe/app/monitor/monitorService/monitorServiceImpl"
	"github.com/bzdanny/BaiZe/app/routes"
	"github.com/bzdanny/BaiZe/app/system/systemController"
	"github.com/bzdanny/BaiZe/app/system/systemDao/systemDaoImpl"
	"github.com/bzdanny/BaiZe/app/system/systemService/systemServiceImpl"
	"github.com/bzdanny/BaiZe/baize/datasource"
	"github.com/bzdanny/BaiZe/baize/setting"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func wireApp(settingDatasource *setting.Datasource) (*gin.Engine, func(), error) {
	data, cleanup, err := datasource.NewData(settingDatasource)
	if err != nil {
		return nil, nil, err
	}
	sysDictDataDao := systemDaoImpl.NewSysDictDataDao()
	dictDataService := systemServiceImpl.NewDictDataService(data, sysDictDataDao)
	dictDataController := systemController.NewDictDataController(dictDataService)
	sysDictTypeDao := systemDaoImpl.NewSysDictTypeDao()
	dictTypeService := systemServiceImpl.NewDictTypeService(data, sysDictTypeDao)
	dictTypeController := systemController.NewDictTypeController(dictTypeService)
	sysUserDao := systemDaoImpl.GetSysUserDao()
	sysPermissionDao := systemDaoImpl.NewSysPermissionDao()
	sysRoleDao := systemDaoImpl.NewSysRoleDao()
	logininforDao := monitorDaoImpl.NewLogininforDao()
	loginService := systemServiceImpl.NewLoginService(data, sysUserDao, sysPermissionDao, sysRoleDao, logininforDao)
	sysUserPostDao := systemDaoImpl.NewSysUserPostDao()
	sysUserRoleDao := systemDaoImpl.NewSysUserRoleDao()
	userService := systemServiceImpl.NewUserService(data, sysUserDao, sysUserPostDao, sysUserRoleDao)
	loginController := systemController.NewLoginController(loginService, userService)
	sysPostDao := systemDaoImpl.NewSysPostDao()
	postService := systemServiceImpl.NewPostService(data, sysPostDao)
	sysRolePermissionDao := systemDaoImpl.NewSysRolePermissionDao()
	sysRoleDeptDao := systemDaoImpl.NewSysRoleDeptDao()
	roleService := systemServiceImpl.NewRoleService(data, sysRoleDao, sysRolePermissionDao, sysRoleDeptDao, sysUserRoleDao)
	userController := systemController.NewUserController(userService, postService, roleService)
	sysDeptDao := systemDaoImpl.NewSysDeptDao()
	deptService := systemServiceImpl.NewDeptService(data, sysDeptDao, sysRoleDao)
	deptController := systemController.NewDeptController(deptService)
	roleController := systemController.NewRoleController(roleService)
	postController := systemController.NewPostController(postService)
	permissionService := systemServiceImpl.NewPermissionService(data, sysPermissionDao, sysRolePermissionDao, sysRoleDao)
	permissionController := systemController.NewPermissionController(permissionService)
	profileController := systemController.NewProfileController(roleService, postService, userService)
	systemControllerSystemController := systemController.NewTenantController(dictDataController, dictTypeController, loginController, userController, deptController, roleController, postController, permissionController, profileController)
	infoServerController := monitorController.NewInfoServerController()
	logininforService := monitorServiceImpl.GetLogininforService(data, logininforDao)
	logininforController := monitorController.NewLogininforController(logininforService)
	userOnlineService := monitorServiceImpl.NewUserOnlineService()
	userOnlineController := monitorController.NewUserOnlineController(userOnlineService)
	monitorControllerMonitorController := monitorController.NewMonitorController(infoServerController, logininforController, userOnlineController)
	router := routes.NewRouter(systemControllerSystemController, monitorControllerMonitorController)
	engine := newApp(router)
	return engine, func() {
		cleanup()
	}, nil
}
