name: "baize"
mode: "dev" #dev 开发模式，日志打印到控制台，prod  生产模式，日志不打印控制台
port: 8080
version: "v1.0.0"
start_time: "2022-08-08"  #此日期用于雪花算法
host: http://localhost:8080
log:
  level: "info"
  filename: /Volumes/disk01/baizelog/baizelog.log
  max_size: 200
  max_age: 30
  max_backups: 7
datasource:
  master:
    driver_name: "mysql"
    host: "116.63.188.235"
    user: "root"
    password: "1q2w3e4r5t@"
    dbname: "baize"
    port: 3306
    max_open_conns: 200
    max_idle_conns: 50
  slave:
    count: 1
    driver_name: "mysql"
    hosts: "140.210.199.226"
    users: "root"
    passwords: "1q2w3e4r5t@"
    dbnames: "baize"
    ports: 3306
    max_open_conns: 200
    max_idle_conns: 50
  redis:
    host: 116.63.188.235
    port: 6379
    password: 1q2w3e4r5t~
    db: 0
    pool_size: 100
  mq:
    amqp:
      host: "122.9.137.57"
      port: 5672
      user: "root"
      password: "1q2w3e4r5t~"

token:
  expire_time: 600
  secret: abcdefghijklmnopqrstuvwxyz
  issuer: baize

upload_file:
  type: aws    #上传地点   亚马逊->s3  移动云->eos 本地->localhost(集群部署会出问题,不建议使用)
  domain_name: https://file.ibaize.vip
  s3:
    access_key_id: AKIARVNELFPCUIHRDIUA
    Secret_access_key: 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
    region: ca-central-1
    bucket_name: file.ibaize.vip
  eos:
    access_key_id: AKIARVNELFPCUIHRDIUA
    Secret_access_key: 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
    url: https://eos-wuxi-1.cmecloud.cn   #移动云eos节点url
    bucket_name: file.ibaize.vip
  localhost:
    public_resource_prefix: /Volumes/disk01/pub
    private_resource_prefix: /Volumes/disk01/pri