name: "baize"
mode: "dev" #dev 开发模式，日志打印到控制台，prod  生产模式，日志不打印控制台
port: 8080
version: v2.0.0
start_time: 2022-08-08  #此日期用于雪花算法
host: http://localhost:8080
log:
  level: info
  filename: /Volumes/disk01/baizelog/baizelog.log
  max_size: 200
  max_age: 30
  max_backups: 7
datasource:
  master:
    driver_name: mysql
    host: 127.0.0.1
    user: root
    password: 123456
    dbname: baize
    port: 3306
    max_open_conns: 200
    max_idle_conns: 50
  slave:
    count: 1
    driver_name: mysql
    hosts: 127.0.0.1
    users: root
    passwords: 123456
    dbnames: baize
    ports: 3306
    max_open_conns: 200
    max_idle_conns: 50
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    db: 0
    pool_size: 100
  mq:
    amqp:
      host: 127.0.0.1
      port: 5672
      user: root
      password: 123456

token:
  expire_time: 600
  secret: abcdefghijklmnopqrstuvwxyz
  issuer: baize

upload_file:
  type: s3    #上传地点 本地->localhost(集群部署需要做硬盘挂载,挂载路径需一直)  亚马逊->s3   移动云->eos  如果不填则默认本地当前目录
  domain_name: https://file.ibaize.vip
  localhost:
    public_resource_prefix: /Volumes/disk01/public/   #如果type=localhost不填则默认启动目录./file/public
    private_resource_prefix: /Volumes/disk01/private/ #如果type=localhost不填则默认启动目录./file/public
  s3:
    access_key_id: xxx
    Secret_access_key: xxx
    region: ca-central-1
    bucket_name: file.ibaize.vip
  eos:
    access_key_id: xxx
    Secret_access_key: xxx
    url: https://eos-wuxi-1.cmecloud.cn   #移动云eos节点url
    bucket_name: file.ibaize.vip
